fm_elfinder:
    assets_path: /assets
    instances:
        default:
            locale: fr
            editor: ckeditor
            theme: smoothness
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/images
                        show_hidden: false
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

