# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        square:
            quality: 75
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: outbound
        banniere:
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    size: [800, 400]
                    mode: outbound
